### ISSUE TITLE
Set up unit testing

### ISSUE THREAD

**Issue by deltaidea** [suclearnub/budgetsim#8]
See #7.

I'll try to start myself. I'll use [Catch](https://github.com/philsquared/Catch).

**Comment by deltaidea** [comment]
Just wait a little. I'll submit a PR so that we can discuss the details together.

**Comment by deltaidea** [comment]
C++ is a pain in the butt. But I'm not giving up.

**Comment by the-emerald** [comment]
I'll definitely agree with you - C++ is really confusing.

**Comment by seanballais** [comment]
@suclearnub Nah, not really. Haha.
@deltaidea Go do that stuff. I'll just catch along.
